# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.cors {
  allowedOrigins = ["http://localhost:4200"]
  allowedHttpMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
}